### ISSUE TITLE
TopologicalError after installing using conda

### ISSUE THREAD

**Issue by rohmaneo** [OpenTopography/RiverREM#6]
Hi there, first of all good job for the REM. It is an outstanding idea and very interesting approach.
Because of it, i really wanna try it for my study area for landslide mapping. 

How ever when i try installing using conda. An error related to Shapely occurs. 
I tried looking for the Shapely version used in the documentation. but can't find any information.
I tried updating my Shapely as well, but the error remains.
![eor](https://github.com/OpenTopography/RiverREM/assets/82828935/ca24aea7-903c-4820-b4cc-e8c0f1e99fd6)

Can someone give some suggestions regarding this issue?

**Comment by klarrieu** [comment]
Hello,

Thanks for the kind words. It appears you may have incompatible versions of
osmnx and shapely installed in your conda environment. See for example
here:
https://stackoverflow.com/questions/75025513/is-this-a-general-bug-of-osmnxs-installation-cannot-import-shapely-geos-impor

I think the easiest solution would likely be to create a new conda
environment for running riverrem, e.g. using

conda create -n <env_name> riverrem

Then try again using that new environment. If the issue still persists, let
me know what versions of python, osmnx and shapely do you have in your
environment so I can try to help troubleshoot further. Thanks.

Best,
Kenny

**Comment by rohmaneo** [comment]
Dear Kenny,

Thank you for the prompt reply.....
It works.... !!!!
All your suggestions solved the error and i can generate REM from my DEM.
Now i will try producing my own river center line and see if it works.

Thanks again...!!

Best,
Neo
